### ISSUE TITLE
Did you reproduce the paper result?

### ISSUE THREAD

**Issue by twmht** [xfey/pytorch-BigNAS#1]
From the paper they sample a few good models.

Have you reproduced the similar results?

**Comment by xfey** [comment]
Thanks for following this repo. As mentioned in the "Result" section, we are currently running this code and waiting for the results, which are expected to be available by _July 20_ if everything goes well.

We are following configurations from [AttentiveNAS](https://github.com/facebookresearch/AttentiveNAS/blob/main/configs/train_attentive_nas_models.yml). However, since we have reduced the number of running GPUs, the exact results may vary depending on the different hyperparameters. Therefore, we hoped that the changes made would have as little impact as possible on the training process.

Besides, if you use this code to run and get some results, we'd appreciate it if you could provide them via Pull Requests 👏.

**Comment by twmht** [comment]
Why it takes so long? I am going to train with this repo. I think the performance can be improved a lot if you use Nvidia Dali as the data loader.

**Comment by xfey** [comment]
Following AttentiveNAS we train this code for 5+360 epochs, and the _sandwich rule_ requires 4 architectures to be sampled in each epoch, thus the total number of epochs reaches 4\*(5+360)=1460. Other methods, such as calibrating BN running statistics, also incur time overhead in their computation.

DALI defines & uses its transform functions in the `dali.Pipeline` type. However, this code uses `AutoAugment` to build transformations for images, but the [transformation functions](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.transforms.html) provided by DALI cannot meet the requirements of `AutoAugment`.
